# This file was generated by GoReleaser. DO NOT EDIT.
class ChannelBookingGenerator < Formula
  desc "Software to create generation uuid for all steps from channel to booking."
  homepage "https://redeam.com"
  version "0.2.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/NickTaporuk/channels_booking_clients/releases/download/v0.2.5/channels_booking_clients_Darwin_x86_64.zip"
    sha256 "a35b88a3e1c944130dfbb29357c26ab8ab40b3d02ae2e81b65aada58fbd54244"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/NickTaporuk/channels_booking_clients/releases/download/v0.2.5/channels_booking_clients_Linux_x86_64.zip"
      sha256 "08c002e3a3e8c4d081ceee8657b2f496033a0f17b5f53fbc31364d3bda46864f"
    end
  end

  def install
    bin.install "channels_booking_clients"
  end
end
