# This file was generated by GoReleaser. DO NOT EDIT.
class 2021aiTest < Formula
  desc "Software to compute data by the original programing language"
  homepage ""
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.3/2021ai_test_Darwin_x86_64.tar.gz"
    sha256 "e85639ce6a87aa19f83b9f2c2103c51b41d13de92b84dfd236c933f5e39868ac"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.3/2021ai_test_Linux_x86_64.tar.gz"
      sha256 "a244ab9c81298a8cad18052ef3c2ffb19433774228d01d646c581446a553696e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.3/2021ai_test_Linux_arm64.tar.gz"
        sha256 "beb5aafe534cfb9bd3c136bc76dfa9cc9d75bed092200e373b8b4d753189b577"
      else
        url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.3/2021ai_test_Linux_armv6.tar.gz"
        sha256 "dd1ae87a3a88b903f489d7febbb92b1d9c60fa6199a8fd3214d93ae1390f030e"
      end
    end
  end

  def install
    bin.install "2021ai_test"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
