# This file was generated by GoReleaser. DO NOT EDIT.
class 2021aiTest < Formula
  desc "Software to compute data by the original programing language"
  homepage ""
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.2/2021ai_test_Darwin_x86_64.zip"
    sha256 "af02f9731b332617df16b7c04aef5692aa838d37da08346cb8d0b18801da11e3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.2/2021ai_test_Linux_x86_64.zip"
      sha256 "f9cafb64ae7b44f137e61caeca9b30dc68ddf7b39becadb272ed82d729eae9a6"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.2/2021ai_test_Linux_arm64.zip"
        sha256 "dbb1cda0d57e77073986a2beef502a13eda9eec3893bfdf42ad98cf66da22455"
      else
        url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.2/2021ai_test_Linux_armv6.zip"
        sha256 "6b0803258f3a22b96914553de9fee30f03fd37103233b9e37695371002ba3c7a"
      end
    end
  end

  def install
    bin.install "2021ai_test"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
