# This file was generated by GoReleaser. DO NOT EDIT.
class ChannelBookingGenerator < Formula
  desc "Software to create generation uuid for all steps from channel to booking."
  homepage ""
  version "0.2.6"

  if OS.mac?
    url "https://github.com/NickTaporuk/channels_booking_clients/releases/v0.2.6/channels_booking_clients_Darwin_x86_64.zip"
    sha256 "6c9bcca784d8cc02aa4a1d0e524e7cb593177d887f9b24df590b9909e8f9ea8b"
  elsif OS.linux?
    url "https://github.com/NickTaporuk/channels_booking_clients/releases/v0.2.6/channels_booking_clients_Linux_x86_64.zip"
    sha256 "41e9a50a5fa4b313e4fb6d1d371d99cc0d284c59714a503bd72127cd2fc16104"
  end

  def install
    bin.install "channels_booking_clients"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
