# This file was generated by GoReleaser. DO NOT EDIT.
class ChannelsBookingClients < Formula
  desc "Software to create generation uuid for all steps from channel to booking."
  homepage ""
  version "1.0.1"

  if OS.mac?
    url "https://github.com/NickTaporuk/channels_booking_clients/releases/download/v1.0.1/channels_booking_clients_Darwin_x86_64.zip"
    sha256 "7e41e07bfe8e676429247d4d29fc6dd390e013c54196bc18e3ac49d25e51c1d4"
  elsif OS.linux?
    url "https://github.com/NickTaporuk/channels_booking_clients/releases/download/v1.0.1/channels_booking_clients_Linux_x86_64.zip"
    sha256 "5187fa078b51df53840adbf1d82625f83116cca3618ac3aa7e7845506087c69a"
  end

  def install
    bin.install "channels_booking_clients"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
