# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gigamock < Formula
  desc "Software to make a mock of REST API or work with kafka messages."
  homepage ""
  version "0.1.6"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/NickTaporuk/gigamock/releases/download/v0.1.6/gigamock_Darwin_x86_64.zip"
    sha256 "f14f9964b766ded41e08f54c7a700357fb3be2295842884e2cece13ef5ad8cf8"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/NickTaporuk/gigamock/releases/download/v0.1.6/gigamock_Darwin_arm64.zip"
    sha256 "3657bbf886f5842f39108c88358f89ea42200a69fca05dbcb9dc029ff863b5c9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/NickTaporuk/gigamock/releases/download/v0.1.6/gigamock_Linux_x86_64.zip"
    sha256 "28f366d8ca6226cd59b5eb159a82b1c5396eba2505c5a452ac62382e2f680e58"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/NickTaporuk/gigamock/releases/download/v0.1.6/gigamock_Linux_armv6.zip"
    sha256 "ae61a8ac6e53dba2827cc5307d261af8a50c99db5494ff55e7a346e93f1de9a2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/NickTaporuk/gigamock/releases/download/v0.1.6/gigamock_Linux_arm64.zip"
    sha256 "5fa9427721bdc133381dde5edd498d217a732dab200f7fc336248444d6eebc9d"
  end

  def install
    bin.install "gigamock"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
