# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gigamock < Formula
  desc "Software to make a mock of REST API or work with kafka messages."
  homepage ""
  version "0.1.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/NickTaporuk/gigamock/releases/download/v0.1.4/gigamock_Darwin_x86_64.zip"
    sha256 "cfacdfcc982945c009114a5cefd2d25d5d2a2402b0e0a37c27cdc0bf43f1798d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/NickTaporuk/gigamock/releases/download/v0.1.4/gigamock_Darwin_arm64.zip"
    sha256 "8520f54eb97b9e5fc39d96cd318c8569c15c01630d431820cc08b784810b29b0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/NickTaporuk/gigamock/releases/download/v0.1.4/gigamock_Linux_x86_64.zip"
    sha256 "21476901ac197f3bc55ded0085e49d831a7d3078dbe8f58aafa4ddb883d96da5"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/NickTaporuk/gigamock/releases/download/v0.1.4/gigamock_Linux_armv6.zip"
    sha256 "bc3f7ecfe3f1bc052a63bde3a0fd4f2eb9fc849e90c3839ffb6e9aa632417d5e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/NickTaporuk/gigamock/releases/download/v0.1.4/gigamock_Linux_arm64.zip"
    sha256 "58abee897f1e5b999281e38861b2f07c31ef96ef6de5e224fe5a6a0daae86cdf"
  end

  def install
    bin.install "gigamock"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
