# This file was generated by GoReleaser. DO NOT EDIT.
class Scalc < Formula
  desc "Software to compute data by the original programing language"
  homepage ""
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.4/2021ai_test_Darwin_x86_64.tar.gz"
    sha256 "d1f1d81b629007d83a5da1ec873f0defc19cd1ffcc3acf43ddd1c97825565b6d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.4/2021ai_test_Linux_x86_64.tar.gz"
      sha256 "8c3b8c0d8b8b4ea37cdd2c1242c88ea99511328e714bab4610d6143e35fa7b17"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.4/2021ai_test_Linux_arm64.tar.gz"
        sha256 "2d3bea454078753678e4e62e2fdd6664f56565be0f96c1a8abeffd7e20174fca"
      else
        url "https://github.com/NickTaporuk/2021ai_test/releases/download/v0.0.4/2021ai_test_Linux_armv6.tar.gz"
        sha256 "0c60fba6e904562f0b6edceba3ca6f025199f8fd99bf513c84e296f95c7b4532"
      end
    end
  end

  def install
    bin.install "scalc"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
